name: totem_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^0.3.2
  circular_reveal_animation: ^2.0.0
  connectivity_plus: ^1.0.6
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  fdottedline: ^1.0.1
  firebase_auth: ^3.1.0
  flutter_facebook_login: ^3.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_slidable: ^0.6.0
  flutter_spinkit: 4.1.2+1
  flutter_svg: ^0.22.0
  get: ^4.1.4
  get_storage: ^2.0.2
  google_sign_in: ^5.0.7
  http: ^0.13.3
  image_picker: ^0.8.3+2
  intl: ^0.17.0
  pin_code_fields: ^7.2.0
  pinput: ^1.2.0
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^3.2.0
  simple_animations: ^3.1.1
  flutter_easyloading: 2.2.2
  cached_network_image: any
  skeleton_loader: any
  flutter_multi_formatter: ^2.3.2
  carousel_slider: ^4.0.0
  country_code_picker: any
  flutter_staggered_grid_view: ^0.4.0
  image_cropper: ^1.4.1
  flutter_image_compress: ^1.0.0
  google_maps_flutter: any  
  google_maps_webservice: ^0.0.20-nullsafety.5
  geocoder: any
  url_launcher: ^6.0.9
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.0.1
  flutter_reaction_button: ^1.0.8
  video_thumbnail: ^0.4.3
  video_player: ^2.1.12
  image: ^3.0.2
  path: ^1.8.0
  media_picker_builder: ^1.3.2
  permission_handler: ^8.1.4+2
  firebase_dynamic_links: ^2.0.8
  firebase_messaging: ^10.0.3
  flutter_share: ^2.0.0
  pull_to_refresh: ^2.0.0
  volume: ^1.0.1
  photo_view: ^0.12.0
  flick_video_player: ^0.3.1
  visibility_detector: ^0.2.0
  native_admob_flutter: ^1.5.0
  webview_flutter: ^2.0.10
  video_editor: ^1.2.0
  helpers: ^1.1.4
  package_info_plus: ^1.3.0
  firebase_analytics: ^8.3.4
  flutter_intro: ^2.3.1
  collection: any
  #tutorial_coach_mark: ^1.2.1
  #highlighter_coachmark: ^0.0.3
  #showcaseview: ^1.1.4

#  hive: ^2.0.4
#  hive_flutter: ^1.1.0
#  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
#  hive_generator: ^1.1.1
#  build_runner: ^2.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg_image/
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: Poppins Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
